### PR TITLE
add checkpoint_dir content-type, remove checkpoint variant

### PR DESCRIPTION
**Pull request by bertsky**
This removes the older of the two parameterizations (a direct Calamari-like glob expression) in favour of the newer, more OCR-D-like model directory, and adds a proper `format` and `content-type` as required by the specs for optimal `resmgr` handling.

### CODE REVIEW

**Review by kba — APPROVED** [review]

**Comment by bertsky** [comment]
I had to fix the tests as well. We could also use `kant_aufklaerung_1784-binarized` instead of `kant_aufklaerung_1784-page-region-line-word_glyph` to get binary input without the need for ad-hoc IM binarization BTW.

**Comment by mikegerber** [comment]
It's a bit unfortunate to drop the former default checkpoint-parameter, is there really no way to still support this and phase it out afterwards?

**Comment by bertsky** [comment]
> It's a bit unfortunate to drop the former default parameter `checkpoint`, is there really no way to still support this and phase it out afterwards?

No, unfortunately I can't see any. We had to get to terms with our file vs directory resources and the semantics of `content-type` in a ocrd-tool.json – see related discussions in core. Unless we make the resource mechanism much more complicated (by specifying which params can have which resources), if we want to properly support directories as a resource type, individual processors should not have both.

**Comment by mikegerber** [comment]
I've also removed the `checkpoint` mention in the README in 33f5d63!

**Pull request merged**
