### PR TITLE
recognize: skip tiny or bin-empty lines, too

### PR DESCRIPTION
**Pull request by bertsky**

### CODE REVIEW

**Review by mikegerber — APPROVED** [review]
While I sympathize with these changes: Is this filter not something that would be useful in other processors, too? I.e. go to the core library?

@kba Your thoughts on this?

**Comment by mikegerber** [comment]
It could also go to a generic filter-cleaner processor.

**Comment by bertsky** [comment]
> It could also go to a generic filter-cleaner processor.

Indeed. It makes sense to do that as a postprocessing step, depending on the workflow (not all segmenters will need it). I could easily add something along these lines to ocrd-segment-repair.

Until then, let's consider this a robustness feature. (ocrd_tesserocr already does the same filtering.)

**Comment by mikegerber** [comment]
Yeah, I had intended to merge it, I just need to run a quick test later

**Comment by kba** [comment]
> While I sympathize with these changes: Is this filter not something that would be useful in other processors, too? I.e. go to the core library?

Such a filter would make sense to have in core but where would we add it? To the `get_TextLine()` method in the PAGE API?

**Comment by bertsky** [comment]
> Such a filter would make sense to have in core but where would we add it? To the `get_TextLine()` method in the PAGE API?

If in core as part of OcrdPage, I'd rather place it on the producer side: `TextLineType` constructor and `.set_Coords()`. (Where it's easy to check the bbox dimensions, but checking for binary-empty is challenging – it would involve looking up the line's binarized AlternativeImage, or its parent's etc.) Perhaps even just `CoordsType` constructor and `.set_points()` (which we already patch for another reason).

Also, what about the GdsCollector mechanism?

**Pull request merged**
