### PR TITLE
check for empty line image, ht @andbue, fix #48

### LINKED ISSUE #48: Handle empty images gracefully
> OK, I've installed OCR-d for the first time, it worked in most parts out of the box and I was able to reproduce the problem. Your errors seem to be caused by OCR-d processors, not by calamari.
Somehow the line segmentation produces empty lines or lines that are outside of text regions. When the empty images are converted to numpy (by ocrd_calamari, not by calamari), numpy throws an uncaught exception. You could fix it by inserting before [line 77 in ocrd_calamari/recognize.py](https://github.com/OCR-D/ocrd_calamari/blob/1c7fcda767ef35c0a19171bddfd82aac36207e81/ocrd_calamari/recognize.py#L77) something like `line_image = line_image if all(line_image.size) else [[0]]`, but that's only a temporary hack to avoid the error. I'm also not sure if their workspace.image_from_segment or even the line segmentation processor is supposed to produce empty lines at all, so maybe the real problem is somewhere deeper in the guts of the OCR-d machinery.

_Originally posted by @andbue in https://github.com/Calamari-OCR/calamari/issues/193#issuecomment-746979800_

### PR DESCRIPTION
**Pull request by kba**
@jbarth-ubhd Can you please verify that this fixes https://github.com/Calamari-OCR/calamari/issues/193 / #48 for you?

### CODE REVIEW

**Comment by jbarth-ubhd** [comment]
@kba: are you using github cli, too?
```
[hd_xxxxx@login5 ocrd_calamari]$ ~/gh_1.4.0_linux_amd64/bin/gh pr checkout 49
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Total 4 (delta 3), reused 4 (delta 3), pack-reused 0
Entpacke Objekte: 100% (4/4), 418 Bytes | 2.00 KiB/s, Fertig.
Von https://github.com/OCR-D/ocrd_calamari
 * [neuer Branch]    fix-48     -> origin/fix-48
Vorherige Position von HEAD war 1c7fcda 📝 README: Link to model download
Zu neuem Branch 'fix-48' gewechselt
```

**Comment by jbarth-ubhd** [comment]
what should I do?
```
[hd_xxxxx@login5 ocrd_all]$ make OCRD_MODULES=ocrd_calamari NO_UPDATE=1 all
make: Nothing to be done for `all'.
```
but without NO_UPDATE=1 I'll assume version of ocrd_calamari will be set back...

**Comment by kba** [comment]
> what should I do?
> 
> ```shell
> [hd_xxxxx@login5 ocrd_all]$ make OCRD_MODULES=ocrd_calamari NO_UPDATE=1 all
> make: Nothing to be done for `all'.
> ```
> 
> but without `NO_UPDATE=1` I'll assume version of ocrd_calamari will be set back...

Quick way to trigger a rebuild is to remove the `ocrd-calamari-recognize` wrapper:

```
rm venv/bin/ocrd-calamari-recognize
make all OCRD_MODULES=ocrd_calamari NO_UPDATE=1
```
```

**Comment by jbarth-ubhd** [comment]
yes, this pr helps for calamari#193, but not for

» ValueError: Error when checking input: expected input_1 to have shape (448, 896, 3) but got array with shape (448, 4, 3)
https://digi.ub.uni-heidelberg.de/diglitData/v/ocrd/lichtwark1932bd2_-_h.tif«.

I will open a separate case for that.

**Comment by mikegerber** [comment]
I'll check this PR this week.

**Comment by mikegerber** [comment]
This fixed #48, merging!

**Pull request merged**
