### PR TITLE
ocrd-tool.json: add public v1 models

### PR DESCRIPTION
**Pull request by bertsky**
This adds the preconfigured resources – so far managed under core's ocrd/resource_list.yml.

Unfortunately, pending https://github.com/Calamari-OCR/calamari_models/issues/11, we cannot add more v1 models at the moment.

### CODE REVIEW

**Comment by bertsky** [comment]
Ok, so since TF 2.16 is out, our v1 does [not work](https://app.circleci.com/pipelines/github/OCR-D/ocrd_calamari/275/workflows/115c33e5-a1cf-4ac7-9cfb-31b690edc7d8/jobs/572) anymore – affects Py 3.9 onwards. We should hold at <2.16 so Keras can stay <3.0.

**Comment by bertsky** [comment]
What's going on with the CI here? I fixed it above (by avoiding Keras v3), but now it says that it cannot checkout the PR – ???

**Review by mikegerber — APPROVED** [review]
LGTM

**Comment by mikegerber** [comment]
The original CI failure was probably just some hickup. 

But the JSON was invalid, I fixed it and the tests ran successfully now. I'd like to run some manual tests before merging.

**Comment by mikegerber** [comment]
At least for `idiotikon` this unpacks an extra sub-directory, e.g. `/home/b-mg106/.local/share/ocrd-resources/ocrd-calamari-recognize/idiotikon/idiotikon`, so this is not ready for merging, unfortunately.

**Comment by mikegerber** [comment]
Checklist (incomplete):

- [ ] `qurator-gt4histocr-1.0`
- [ ] `zpd-fraktur19`
- [ ] `zpd-latin-script-hist-3`

Didn't check the models themselves, just if the result of the download looked right.

**Comment by mikegerber** [comment]
This looks good now, after fixing the downloads + some superficial testing.

**Comment by bertsky** [comment]
Sorry, I should have tested this better. Thanks!

**Pull request merged**
