### PR TITLE
⚙ Migrate from setup.py to pyproject.toml

### LINKED ISSUE #103: Migrate to pyproject.toml
- [x] Migrate to pyproject.toml
  - [x] setup.py
  - [x] .coveragerc
  - [x] .ruff.toml
- [x] #85
- [x] Review keywords
- [x] Review classifiers
- [x] license.file?
- [x] Review mypy (copied from dinglehopper's config - do we want this here?)
- [x] Check if the coverage config is working
- [x] Remove workaround for core#1262

I'm going to use setuptools-ocrd for this (as the second project using it). If OCR-D decides against using it I can still change the project back to whatever OCR-D agrees upon.

### PR DESCRIPTION
**Pull request by mikegerber**
Migrate from `setup.py` to `pyproject.toml`.

This uses [setuptools-ocrd](https://github.com/qurator-spk/setuptools_ocrd/) to source the `version` from `ocrd-tool.json`.

Closes #103.

### CODE REVIEW

**Comment by mikegerber** [comment]
CI failure are due

- 3.7: not supported by setuptools-ocrd → Remove support for 3.7 here as well (3.7 is EOL)
- 3.8+: This is a problem in OCR-D/core (https://github.com/OCR-D/core/issues/1262)

**Comment by mikegerber** [comment]
Seeking review from @bertsky and @kba, for feedback on setuptools-ocrd.

setuptools-ocrd does two things:

- Source the Python package `version` from `ocrd-tool.json`
- Makes sure `ocrd-tool.json` (including symlink) goes into the sdist package (so a wheel can be built from the sdist, needed for e.g. `build`; this is not super obvious, but definitely needed)

**Comment by mikegerber** [comment]
Install seems to be functional, if ocrd is downgraded to 2.67.0.

**Comment by mikegerber** [comment]
Removing draft status; This is ready (except for the removal of the workaround for core#1262)

**Review by mikegerber — COMMENTED** [review]
Self-reviewing:

I'm happy with it, the big issue is the version number and setuptools-ocrd takes care of that nicely. (Getting it from git would be another way, but as that does not solve putting the version into ocrd-tool.json, it's best to source it from there.)

**Comment by bertsky** [comment]
> setuptools-ocrd does two things:
> 
> * Source the Python package `version` from `ocrd-tool.json`
> * Makes sure `ocrd-tool.json` (including symlink) goes into the sdist package (so a wheel can be built from the sdist, needed for e.g. `build`; this is not super obvious, but definitely needed)

Please help me understand: How does it do the latter? So far we always had to create a `MANIFEST.in` with include directives for ocrd-tool.json (and readme and requirements.txt)...

**Comment by mikegerber** [comment]
> Please help me understand: How does it do the latter? So far we always had to create a `MANIFEST.in` with include directives for ocrd-tool.json (and readme and requirements.txt)...

It's a setuptools plugin and includes a "file finder" hook ("entry point") to include the file (and symlink):

https://github.com/qurator-spk/setuptools_ocrd/blob/master/pyproject.toml#L38-L39
https://github.com/qurator-spk/setuptools_ocrd/blob/master/setuptools_ocrd/_integration/setuptools.py#L30-L40

AFAICT `README.md` and `requirements.txt` is included by default, at least for dinglehopper (I checked https://github.com/qurator-spk/dinglehopper/releases/download/v0.9.7/dinglehopper-0.9.7.tar.gz sdist), because they are referenced in https://github.com/qurator-spk/dinglehopper/blob/master/pyproject.toml "the correct way" (my theory, no conscious effort).

**Comment by mikegerber** [comment]
Forgot, that I wrote something about this:

https://github.com/qurator-spk/setuptools_ocrd/blob/master/README-DEV.md#how-does-it-work

**Comment by mikegerber** [comment]
> So far we always had to create a `MANIFEST.in` with include directives for ocrd-tool.json (and readme and requirements.txt)...

Was that for `setup.py` projects? That would possibly explain it.

**Comment by mikegerber** [comment]
There's also this GitHub Actions workflow that goes with it:

https://github.com/qurator-spk/dinglehopper/blob/master/.github/workflows/release.yml

The manual install of setuptools-ocrd is needed there so that the script can check the version in `ocrd-tool.json` against the git tag (at least I think it was needed, but not for the build itself because that the build is done in a separate build environment which is set up by the build process).

It is meant to be as reusable as possible and automate away a. the release on the GitHub b. the PyPI release. (I had a bit trouble to make it even more reusable due to some issue with PyPI credentials, but that was months ago I can't say much about the details anymore.)

**Comment by mikegerber** [comment]
> The manual install of setuptools-ocrd is needed there so that the script can check the version in `ocrd-tool.json` against the git tag 

No, actually the Python package version vs the git tag:

https://github.com/qurator-spk/dinglehopper/blob/master/.github/workflows/release-check-version-tag

(and the package version is taken from ocrd-tool.json via setuptools-ocrd).

Anyway, this is the most consistent method I could think of, given that the version field must be in `ocrd-tool.json`.

**Comment by bertsky** [comment]
> There's also this GitHub Actions workflow that goes with it:
> 
> https://github.com/qurator-spk/dinglehopper/blob/master/.github/workflows/release.yml

**Amazing!**

**Comment by mikegerber** [comment]
> **Amazing!**

Yeah I hope a number of people can benefit from reusing this neatly shaved yak.

**Pull request merged**
